/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:51:15 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/Frameworks/MediaPlayer.framework/MediaPlayer
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/


#import <MediaPlayerUI/MPAVRoutingControllerDelegate-Protocol.h>
#import <MediaPlayerUI/MPAVRoute.h>

@protocol MPAVRoutingControllerDelegate;
@class NSArray, MPAVRoute, NSMutableArray, NSString;

@interface MPAVRoutingController : NSObject {

	NSArray* _cachedRoutes;
	MPAVRoute* _cachedPickedRoute;
	NSMutableArray* _asyncFetchingCompletionHandlers;
	BOOL _asyncFetchingRoutes;
	NSInteger _externalScreenType;
	BOOL _hasExternalScreenType;
	BOOL _scheduledSendDelegateRoutesChanged;
	BOOL _pickedRouteHasVolumeControl;
	BOOL _hasVolumeControlInfoForPickedRoute;
	int _deviceAvailabilityNotifyToken;
	BOOL _deviceAvailabilityOverrideState;
	id<MPAVRoutingControllerDelegate> _delegate;
	NSString* _name;
	NSInteger _discoveryMode;
	NSString* _category;
	MPAVRoute* _pendingPickedRoute;

}

@property (assign,nonatomic) id<MPAVRoutingControllerDelegate> delegate;              //@synthesize delegate=_delegate - In the implementation block
@property (nonatomic,copy) NSString * name;                                                  //@synthesize name=_name - In the implementation block
@property (assign,nonatomic) NSInteger discoveryMode;                                        //@synthesize discoveryMode=_discoveryMode - In the implementation block
@property (nonatomic,readonly) NSInteger externalScreenType; 
@property (nonatomic,copy,readonly) NSArray * availableRoutes; 
@property (nonatomic,copy) NSString * category;                                              //@synthesize category=_category - In the implementation block
@property (nonatomic,readonly) MPAVRoute * pickedRoute; 
@property (nonatomic,readonly) MPAVRoute * pendingPickedRoute;                               //@synthesize pendingPickedRoute=_pendingPickedRoute - In the implementation block
@property (nonatomic,readonly) BOOL volumeControlIsAvailable; 
-(id)init;
-(void)setDelegate:(id<MPAVRoutingControllerDelegate>)arg1 ;
-(id<MPAVRoutingControllerDelegate>)delegate;
-(void)setName:(NSString *)name;
-(NSString *)name;
-(void)setCategory:(NSString *)category ;
-(NSString *)category;
-(id)initWithName:(NSString *)name ;
-(void)setDiscoveryMode:(NSInteger)discoveryMode;
-(BOOL)volumeControlIsAvailable;
-(MPAVRoute *)pickedRoute;
-(void)clearCachedRoutes;
-(BOOL)pickBestDeviceRoute;
-(NSInteger)externalScreenType;
-(NSArray *)availableRoutes;
-(BOOL)airtunesRouteIsPicked;
-(BOOL)wirelessDisplayRouteIsPicked;
-(BOOL)routeOtherThanHandsetAndSpeakerAvailable;
-(void)_registerNotifications;
-(void)_unregisterNotifications;
-(BOOL)routeOtherThanHandsetAvailable;
-(void)fetchAvailableRoutesWithCompletionHandler:(/*^block*/id)compeletionHandler ;
-(void)_scheduleSendDelegateRoutesChanged;
-(void)_setExternalScreenType:(NSInteger)screenType;
-(void)_updateCachedRoutes;
-(id)_pickedRouteInArray:(NSArray *)routeArray;
-(id)_parseAVRouteDescriptions:(NSArray<NSDictionary *> *)routeDescriptions;
-(BOOL)pickRoute:(MPAVRoute *)route withPassword:(NSString *)password;
-(BOOL)pickRoute:(MPAVRoute *)route;
-(void)_pickableRoutesDidChangeNotification:(NSNotification *)notification;
-(void)_routeStatusDidChangeNotification:(NSNotification *)notification;
-(void)_externalScreenTypeDidChangeNotification:(NSNotification *)notification;
-(void)_activeAudioRouteDidChangeNotification:(NSNotification *)notification;
-(void)_mediaServerDiedNotification:(NSNotification *)notification;
-(id)videoRouteForRoute:(MPAVRoute *)route;
-(BOOL)pickHandsetRoute;
-(BOOL)pickSpeakerRoute;
-(void)unpickAirPlayScreenRouteWithCompletion:(/*^block*/id)completionHandler;
-(BOOL)speakerRouteIsPicked;
-(BOOL)handsetRouteIsPicked;
-(BOOL)receiverRouteIsPicked;
-(BOOL)wirelessDisplayRoutesAvailable;
-(void)logCurrentRoutes;
-(MPAVRoute *)pendingPickedRoute;
-(NSInteger)discoveryMode;
@end
