//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Mar 24 2016 13:14:34).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//


@class MPAVRoute, MPAVRoutingController, NSError;

@protocol MPAVRoutingControllerDelegate

@optional
- (void)routingControllerDidPauseFromActiveRouteChange:(MPAVRoutingController *)routingController;
- (void)routingController:(MPAVRoutingController *)routingController didFailToPickRouteWithError:(NSError *)error;
- (void)routingControllerExternalScreenTypeDidChange:(MPAVRoutingController *)routingController;
- (void)routingController:(MPAVRoutingController *)routingController pickedRouteDidChange:(MPAVRoute *)route;
- (void)routingControllerAvailableRoutesDidChange:(MPAVRoutingController *)routingController;
@end

