/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:56:16 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIView.h>
#import <MediaPlayerUI/MPAVRoute.h>

@interface MPUAVRouteHeaderLabel : UIView {

	NSAttributedString* _primaryLabelAttributedText;
	NSAttributedString* _secondaryLabelAttributedText;
	BOOL _animating;
	BOOL _needsAttributedTextReload;
	BOOL _nextAttributedTextReloadShouldAnimate;
	BOOL _showNowPlayingText;
	BOOL _showPendingText;
	UILabel* _primaryLabel;
	UILabel* _secondaryLabel;
	MPAVRoute* _route;
	UIColor* _primaryTextColor;
	UIColor* _secondaryTextColor;

}

@property (nonatomic,readonly) UILabel * primaryLabel;                       //@synthesize primaryLabel=_primaryLabel - In the implementation block
@property (nonatomic,readonly) UILabel * secondaryLabel;                     //@synthesize secondaryLabel=_secondaryLabel - In the implementation block
@property (nonatomic,readonly) CGFloat baselineOffsetFromBottom; 
@property (nonatomic,retain) MPAVRoute * route;                              //@synthesize route=_route - In the implementation block
@property (assign,nonatomic) BOOL showNowPlayingText;                        //@synthesize showNowPlayingText=_showNowPlayingText - In the implementation block
@property (assign,nonatomic) BOOL showPendingText;                           //@synthesize showPendingText=_showPendingText - In the implementation block
@property (nonatomic,retain) UIColor * primaryTextColor;                     //@synthesize primaryTextColor=_primaryTextColor - In the implementation block
@property (nonatomic,retain) UIColor * secondaryTextColor;                   //@synthesize secondaryTextColor=_secondaryTextColor - In the implementation block
-(id)initWithFrame:(CGRect)frame;
-(void)layoutSubviews;
-(id)initWithCoder:(NSCoder *)coder;
-(CGSize)sizeThatFits:(CGSize)size;
-(void)_init;
-(CGFloat)baselineOffsetFromBottom;
-(UILabel *)secondaryLabel;
-(MPAVRoute *)route;
-(void)setRoute:(MPAVRoute *)route;
-(UIColor *)primaryTextColor;
-(void)setPrimaryTextColor:(UIColor *)color;
-(UIColor *)secondaryTextColor;
-(void)setSecondaryTextColor:(UIColor *)color;
-(void)_setNeedsAttributedTextReloadAnimated:(BOOL)needsReloadAnimated;
-(void)setShowNowPlayingText:(BOOL)showText animated:(BOOL)animated;
-(void)setShowPendingText:(BOOL)showText animated:(BOOL)animated;
-(id)_labelAttributesUsingSecondaryStyle:(BOOL)useSecondaryStyle;
-(id)_currentDeviceConnectingText;
-(id)_currentDeviceLocalRoutingNowPlayingText;
-(void)_reloadAttributedTextAnimated:(BOOL)reloadTextAnimated;
-(id)_stateAwareAttributedTextForRoute:(MPAVRoute *)route usingSecondaryStyleForRouteName:(BOOL)useSecondaryStyle orForNowPlayingText:(BOOL)forNowPlayingText;
-(void)_getAttributedTextForPrimaryLabel:(UILabel *)primaryLabel secondaryLabel:(UILabel *)secondaryLabel;
-(void)setShowNowPlayingText:(BOOL)showText;
-(void)setShowPendingText:(BOOL)showText;
-(UILabel *)primaryLabel;
-(BOOL)showNowPlayingText;
-(BOOL)showPendingText;
@end
