/*
* This header is generated by classdump-dyld 1.0
* on Tuesday, December 27, 2016 at 4:56:16 PM Japan Standard Time
* Operating System: Version 10.1.1 (Build 14B150)
* Image Source: /System/Library/PrivateFrameworks/MediaPlayerUI.framework/MediaPlayerUI
* classdump-dyld is licensed under GPLv3, Copyright © 2013-2016 by Elias Limneos.
*/

#import <UIKit/UIViewController.h>
#import <MediaPlayerUI/MPUChronologicalProgressViewDelegate-Protocol.h>
#import <MediaPlayerUI/MPUTransportControlMediaRemoteControllerDelegate-Protocol.h>
#import <MediaPlayerUI/MPAVRoutingControllerDelegate-Protocol.h>
#import <MediaPlayerUI/MPUNowPlayingDelegate-Protocol.h>
#import <MediaPlayerUI/MPUTransportControlsViewDataSource-Protocol.h>
#import <MediaPlayerUI/MPUTransportControlsViewDelegate-Protocol.h>
#import <MediaPlayerUI/MPUTransportControlsViewLayoutDelegate-Protocol.h>
#import <MediaPlayerUI/MPUMediaRemoteControlsView.h>
#import <MediaPlayerUI/MPUTransportControlMediaRemoteController.h>
#import <MediaPlayerUI/MPAVRoutingController.h>
#import <MediaPlayerUI/MPUVolumeHUDController.h>
#import <MediaPlayerUI/MPUNowPlayingController.h>
#import <MediaPlayerUI/MPUSupportedRemoteControls.h>
#import <MediaPlayerUI/MPAVRoute.h>
#import <MediaPlayerUI/MPUTransportControlsView.h>
#import <MediaPlayerUI/MPUChronologicalProgressView.h>

@interface MPUMediaRemoteViewController : UIViewController <MPUChronologicalProgressViewDelegate, MPUTransportControlMediaRemoteControllerDelegate, MPAVRoutingControllerDelegate, MPUNowPlayingDelegate, MPUTransportControlsViewDataSource, MPUTransportControlsViewDelegate, MPUTransportControlsViewLayoutDelegate> {

	MPUMediaRemoteControlsView* _mediaControlsView;
	MPUTransportControlMediaRemoteController* _transportControlMediaRemoteController;
	MPAVRoutingController* _routingController;
	MPUVolumeHUDController* _volumeHUDController;
	BOOL _showingAsPlaying;
	BOOL _nowPlayingIsRadioStation;
	id _supportedCommandsNotificationToken;
	NSString* _audioCategoryForDisabledHUD;
	NSString* _lastArtworkDigest;
	NSTimer* _scrubberCommitTimer;
	CGFloat _scrubbedTimeDestination;
	CGFloat _lastDurationFromUpdate;
	MPUNowPlayingController* _nowPlayingController;
	MPUSupportedRemoteControls* _supportedRemoteControls;

}

@property (nonatomic,readonly) MPUNowPlayingController * nowPlayingController;                    //@synthesize nowPlayingController=_nowPlayingController - In the implementation block
@property (nonatomic,readonly) MPUSupportedRemoteControls * supportedRemoteControls;              //@synthesize supportedRemoteControls=_supportedRemoteControls - In the implementation block
@property (nonatomic,readonly) NSArray * allowedTransportControlTypes; 
+(Class)controlsViewClass;
+(Class)transportControlButtonClass;
-(void)loadView;
-(void)viewWillAppear:(BOOL)willAppear;
-(void)viewWillDisappear:(BOOL)willDisappear;
-(void)viewDidDisappear:(BOOL)didDisappear;
-(void)viewDidLoad;
-(void)routingControllerAvailableRoutesDidChange:(NSArray<MPAVRoute *> *)availableRoutes;
-(void)_setupNotifications;
-(void)_tearDownNotifications;
-(void)supportedRemoteControlsDidChange;
-(void)nowPlayingController:(MPUNowPlayingController *)nowPlayingController nowPlayingInfoDidChange:(NSDictionary *)info;
-(void)nowPlayingController:(MPUNowPlayingController *)nowPlayingController playbackStateDidChange:(BOOL)didChange;
-(void)nowPlayingController:(MPUNowPlayingController *)nowPlayingController nowPlayingApplicationDidChange:(NSString *)applicationBundleID;
-(void)transportControlsView:(MPUTransportControlsView *)transportControlsView tapOnControlType:(NSInteger)controlType;
-(void)transportControlsView:(MPUTransportControlsView *)transportControlsView longPressBeginOnControlType:(NSInteger)controlType;
-(void)transportControlsView:(MPUTransportControlsView *)transportControlsView longPressEndOnControlType:(NSInteger)controlType;
-(MPUSupportedRemoteControls *)supportedRemoteControls;
-(MPUNowPlayingController *)nowPlayingController;
-(NSString *)remoteControlInterfaceIdentifier;
-(UIButton *)transportControlsView:(MPUTransportControlsView *)transportControlsView buttonForControlType:(NSInteger)controlType;
-(CGSize)transportControlsView:(MPUTransportControlsView *)transportControlsView defaultTransportButtonSizeWithProposedSize:(CGSize)size;
-(void)progressViewDidBeginScrubbing:(MPUChronologicalProgressView *)progressView;
-(void)progressViewDidEndScrubbing:(MPUChronologicalProgressView *)progressView;
-(void)_initMediaRemoteViewController;
-(void)_updateSupportedCommands;
-(void)_stopScrubberCommitTimer;
-(void)_reloadAllowedTransportControls;
-(UIImage *)_imageForTransportButtonWithControlType:(NSInteger)controlType;
-(void)_beginScrubberCommitTimer;
-(void)_commitCurrentScrubberValue;
-(NSArray *)allowedTransportControlTypes;
-(void)_supportedCommandsDidChangeNotification:(NSNotification *)notification;
-(UIViewController *)presentingViewControllerForLikeBanActionSheetForTransportControlMediaRemoteController:(MPUTransportControlMediaRemoteController *)transportControlMediaRemoteController;
-(void)transportControlMediaRemoteController:(MPUTransportControlMediaRemoteController *)transportControlMediaRemoteController requestsPushingMediaRemoteCommand:(unsigned)remoteCommand withOptions:(NSDictionary *)options shouldLaunchApplication:(BOOL)launchApp;
-(void)nowPlayingController:(MPUNowPlayingController *)nowPlayingController elapsedTimeDidChange:(CGFloat)elapsedTime;
@end
