#import <SpringBoardUI/SBUIIconForceTouchController.h>
#import <SpringBoardUI/SBUIForceTouchGestureRecognizer.h>

@protocol SBUIIconForceTouchControllerDataSource <NSObject>
@required
- (CGRect)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController iconViewFrameForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (NSInteger)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController layoutStyleForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (UIView *)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController newIconViewCopyForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (UIViewController *)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController primaryViewControllerForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (UIViewController *)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController secondaryViewControllerForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;

@optional
- (CGFloat)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController iconImageCornerRadiusForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (UIEdgeInsets)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController iconImageInsetsForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (id)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController parallaxSettingsForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (CGFloat)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController wrapperViewCornerRadiusForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (CGPoint)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController zoomDownCenterForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
- (UIView *)iconForceTouchController:(SBUIIconForceTouchController *)iconForceTouchController zoomDownViewForGestureRecognizer:(SBUIForceTouchGestureRecognizer *)gestureRecognizer;
@end

