@interface WiFiNetwork : NSObject <NSCoding, NSCopying> {

	NSMutableDictionary* _dict;
	NSMutableDictionary* _customizedSettings;
	BOOL _available;
	BOOL _dirty;
	BOOL _needsFavoritesCheck;
	NSDictionary* _lastProxyDict;
	NSArray* _certificateChain;
	NSDictionary* _eapolProfile;
	NSArray* _requestedInformation;
	id _tlsIdentity;
	id _wapiRoot;
	id _wapiIdentity;
	BOOL _usernameIsManaged;
	BOOL _hidden;
	BOOL _adhoc;
	BOOL _isHS20;
	BOOL _needsHS20Query;
	BOOL _isHotspotDevice;
	BOOL _isAmbiguousSSID;
	BOOL _isDirectedNetwork;
	BOOL _isLeakyNetwork;
	unsigned _phyMode;

}

@property (assign) BOOL isHotspotDevice;                               //@synthesize isHotspotDevice=_isHotspotDevice - In the implementation block
-(id)proxyPort;
-(id)proxyUsername;
-(id)proxyPassword;
-(id)DNSServers;
-(id)initWithCoder:(id)arg1 ;
-(void)encodeWithCoder:(id)arg1 ;
-(void)dealloc;
-(void)setHidden:(BOOL)arg1 ;
-(id)description;
-(void)setName:(id)arg1 ;
-(id)name;
-(id)dictionary;
-(id)copyWithZone:(NSZone*)arg1 ;
-(BOOL)isSecure;
-(id)proxy;
-(id)strength;
-(void)setDirty:(BOOL)arg1 ;
-(BOOL)dirty;
-(BOOL)hidden;
-(id)certificateChain;
-(void)setAvailable:(BOOL)arg1 ;
-(unsigned)phyMode;
-(BOOL)available;
-(void)setCertificateChain:(id)arg1 ;
-(int)proxyType;
-(void)setUsername:(id)arg1 ;
-(id)username;
-(BOOL)isFavorite;
-(id)router;
-(id)searchDomains;
-(id)BSSID;
-(id)scanResultDictionary;
-(int)configType;
-(void)setConfigType:(int)arg1 userEntered:(BOOL)arg2 ;
-(void)setIP:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)setSubnetMask:(id)arg1 userEntered:(BOOL)arg2 ;
-(id)subnetMask;
-(void)setRouter:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)setDNSServers:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)removeCustomDNSServers;
-(void)setSearchDomains:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)removeCustomSearchDomains;
-(void)setDHCPClientID:(id)arg1 userEntered:(BOOL)arg2 ;
-(id)DHCPClientID;
-(BOOL)IPv6Enabled;
-(id)IPv6Router;
-(id)IPv6Addresses;
-(void)setProxy:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)setProxyPort:(id)arg1 userEntered:(BOOL)arg2 ;
-(BOOL)proxyAuthenticated;
-(void)setProxyAuthenticated:(BOOL)arg1 userEntered:(BOOL)arg2 ;
-(void)setProxyUsername:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)setProxyPassword:(id)arg1 userEntered:(BOOL)arg2 ;
-(void)setProxyType:(int)arg1 userEntered:(BOOL)arg2 ;
-(id)pacFile;
-(void)setPacFile:(id)arg1 userEntered:(BOOL)arg2 ;
-(BOOL)isHostspot20;
-(id)DHCPLeaseExpiration;
-(void)removeCustomIP;
-(void)removeCustomRouter;
-(void)removeCustomSubnet;
-(BOOL)isAdhoc;
-(BOOL)isEnterprise;
-(long long)compareAscending:(id)arg1 ;
-(long long)compareUnconfigAscending:(id)arg1 ;
-(BOOL)isPersonalHotspot;
-(BOOL)canAttemptJoin;
-(BOOL)isHotspotDevice;
-(id)configurationIssues;
-(void)resignActiveNetwork;
-(id)eapolProfile;
-(id)eapTypes;
-(BOOL)requiresTLSIdentityOnly;
-(id)TLSIdentity;
-(void)setEapolProfile:(id)arg1 ;
-(int)securityMode;
-(BOOL)isHostspot20Provisioned;
-(id)WAPIRoot;
-(id)WAPIIdentityPEMBlob;
-(void)setTLSIdentity:(id)arg1 ;
-(void)setWAPIRoot:(id)arg1 ;
-(void)setWAPIIdentityPEMBlob:(id)arg1 ;
-(void)setRequestedInformation:(id)arg1 ;
-(void)resetCustomSettings;
-(int)proxyTypeForDict:(id)arg1 ;
-(void)loadIPv4Dict:(id)arg1 ;
-(void)loadProxyDict:(id)arg1 ;
-(id)initWithWirelessDict:(id)arg1 ;
-(void)setIsHotspotDevice:(BOOL)arg1 ;
-(void)setSecurityMode:(int)arg1 ;
-(BOOL)isAmbiguousSSID;
-(BOOL)requiresSavedPassword;
-(void)setScanResultDictionary:(id)arg1 ;
-(BOOL)needsHotSpot20Query;
-(id)HS20Badge;
-(void)setUsername:(id)arg1 isManaged:(BOOL)arg2 ;
-(void)setIPv4Dict:(id)arg1 ;
-(void)setIPv6Dict:(id)arg1 ;
-(void)setProxyDict:(id)arg1 ;
-(void)setDNSDict:(id)arg1 ;
-(void)setDHCPConfig:(id)arg1 ;
-(id)customSettings;
-(BOOL)supportsWiFiHealth;
-(id)_initWithDictionary:(id)arg1 available:(BOOL)arg2 ;
-(void)_setCustomValue:(id)arg1 forKey:(CFStringRef)arg2 protocol:(CFStringRef)arg3 ;
-(void)setDHCPLeaseExpiration:(id)arg1 ;
-(void)setBSSID:(id)arg1 ;
-(void)setIPv6Addresses:(id)arg1 ;
-(void)setIPv6Router:(id)arg1 ;
-(void)setIPv6Enabled:(BOOL)arg1 ;
-(BOOL)profileContainsEAPSIM:(id)arg1 ;
-(BOOL)profileContainsEAPAKA:(id)arg1 ;
-(BOOL)profileContainsCarrierEAPType:(id)arg1 ;
-(BOOL)requiresPasswordOnly;
-(BOOL)requiresUsernameAndPassword;
-(void)setNeedsFavoritesCheck:(BOOL)arg1 ;
-(BOOL)needsFavoritesCheck;
-(id)lastProxyDictionary;
-(BOOL)isWAPIEnterprise;
-(BOOL)usernameIsManaged;
-(id)requestedInformation;
-(long long)compareDescending:(id)arg1 ;
-(BOOL)isLeakyNetwork;
-(int)profile;
-(void)setProfile:(int)arg1 ;
-(int)age;
-(id)ip;
-(id)password;
-(void)setPassword:(id)arg1 ;
-(BOOL)isEqualTo:(id)arg1 ;
-(void)setIsFavorite:(BOOL)arg1 ;
@end